import type { Params } from "../types";
import { drawCanvasField } from "./canvasFieldKernel";

const vs = `attribute vec2 p;void main(){gl_Position=vec4(p,0.0,1.0);}`;
const fs = `precision mediump float;uniform vec2 r;uniform float t;uniform float w;uniform float d;uniform float s;uniform float e;uniform float n;uniform float m;uniform float g;uniform float z;uniform float seed;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7))+seed*74.7)*43758.5453);}vec3 c(float x){if(x<455.0)return vec3(.45,.3,1.0);if(x<565.0)return vec3(.2,1.0,.5);if(x<610.0)return vec3(1.0,.74,.24);return vec3(1.0,.14,.1);}void main(){vec2 uv=gl_FragCoord.xy/r;vec2 q=(uv-.5)*vec2(r.x/r.y,1.0)*2.0;float rr=length(q);float a=atan(q.y,q.x);float tt=t*(.18+z*.55);float b=8.0+d*34.0;float v=.34+.24*sin((q.x*b+sin(a*3.0+tt)*.45)*3.14159)+.25*sin(rr*(38.0+d*72.0)-tt*5.0+a*(2.0+m*7.0))+.18*sin((q.x+q.y)*b*1.2+tt)*sin((q.x-q.y)*b*1.15-tt)+(h(floor(gl_FragCoord.xy/2.0))-.5)*s*1.8+cos(a*2.0+tt)*exp(-rr*2.5)*e*.32+sin(a*(6.0+n*12.0)+rr*(18.0+n*46.0)-tt*5.5)*n*.20;float i=pow(clamp(v*(.54+.46*max(0.0,1.0-rr*.88)),0.0,1.0),1.25-n*.52);i+=step(.94-g*.28,fract(sin((q.x+q.y+a)*28.0+tt*2.0)*12.731))*g*.22*(1.0-smoothstep(.2,1.25,rr));vec3 col=c(w)*(.12+i*1.22)+vec3(i*.18,i*.06,i*n*.18);gl_FragColor=vec4(col,1.0);}`;

type State={gl:WebGLRenderingContext;program:WebGLProgram;buffer:WebGLBuffer;u:Record<string,WebGLUniformLocation|null>};
const cache=new WeakMap<HTMLCanvasElement,State>();
function makeShader(gl:WebGLRenderingContext,type:number,src:string){const sh=gl.createShader(type);if(!sh)return null;gl.shaderSource(sh,src);gl.compileShader(sh);return gl.getShaderParameter(sh,gl.COMPILE_STATUS)?sh:null;}
function state(canvas:HTMLCanvasElement){const gl=canvas.getContext("webgl",{antialias:false,preserveDrawingBuffer:true});if(!gl)return null;const v=makeShader(gl,gl.VERTEX_SHADER,vs);const f=makeShader(gl,gl.FRAGMENT_SHADER,fs);const program=gl.createProgram();const buffer=gl.createBuffer();if(!v||!f||!program||!buffer)return null;gl.attachShader(program,v);gl.attachShader(program,f);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))return null;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const names=["r","t","w","d","s","e","n","m","g","z","seed"];const u=Object.fromEntries(names.map((name)=>[name,gl.getUniformLocation(program,name)]));const out={gl,program,buffer,u};cache.set(canvas,out);return out;}
export function drawWebglField(canvas:HTMLCanvasElement,params:Params,time:number){canvas.width=720;canvas.height=480;const st=cache.get(canvas)??state(canvas);if(!st){drawCanvasField(canvas,params,time);return;}const {gl,program,buffer,u}=st;gl.viewport(0,0,720,480);gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);const a=gl.getAttribLocation(program,"p");gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);gl.uniform2f(u.r,720,480);gl.uniform1f(u.t,time);gl.uniform1f(u.w,params.wavelength);gl.uniform1f(u.d,params.diffraction);gl.uniform1f(u.s,params.speckle);gl.uniform1f(u.e,params.entoptic);gl.uniform1f(u.n,params.perception);gl.uniform1f(u.m,params.meaning);gl.uniform1f(u.g,params.glyphs);gl.uniform1f(u.z,params.time);gl.uniform1f(u.seed,params.seed);gl.drawArrays(gl.TRIANGLES,0,6);}
